"""drop rss_feed_drafts table

Revision ID: 0052
Revises: 0051
Create Date: 2026-08-31

RSS draft flow removed — ads generated by RSS feeds now go directly to
My Ads in 'ready' (manual) or 'scheduled' (auto-post) state. The draft
table and its approval/dismiss workflow have been replaced by the
standard My Ads review flow.
"""
from alembic import op

revision = '0052'
down_revision = '0051'
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.drop_table('rss_feed_drafts')


def downgrade() -> None:
    import sqlalchemy as sa
    op.create_table(
        'rss_feed_drafts',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('company_id', sa.UUID(), nullable=False),
        sa.Column('subscription_id', sa.UUID(), nullable=False),
        sa.Column('article_url', sa.String(500), nullable=False),
        sa.Column('article_title', sa.String(500), nullable=False, server_default=''),
        sa.Column('article_summary', sa.Text(), nullable=False, server_default=''),
        sa.Column('ad_id', sa.UUID(), nullable=True),
        sa.Column('status', sa.String(20), nullable=False, server_default='pending'),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.id']),
        sa.ForeignKeyConstraint(['subscription_id'], ['rss_feed_subscriptions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['ad_id'], ['ads.id']),
        sa.PrimaryKeyConstraint('id'),
    )
