"""add company_model_config table

Revision ID: 0f71d49bdf73
Revises: 4e5ce0073cf2
Create Date: 2026-07-11 07:57:04.566911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0f71d49bdf73'
down_revision: Union[str, None] = '4e5ce0073cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_model_config',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_model_config')
    # ### end Alembic commands ###
