"""add role_capabilities table

Revision ID: 4e5ce0073cf2
Revises: dc5f7f48d292
Create Date: 2026-07-10 20:12:00.413389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e5ce0073cf2'
down_revision: Union[str, None] = 'dc5f7f48d292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_capabilities')
    # ### end Alembic commands ###
