"""add posted_at and posted_platforms to ads

Revision ID: 5360c8692a49
Revises: a5bb1df8e04d
Create Date: 2026-07-08 20:02:52.406417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5360c8692a49'
down_revision: Union[str, None] = 'a5bb1df8e04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('posted_at', sa.DateTime(), nullable=True))
    op.add_column('ads', sa.Column('posted_platforms', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json")))
    op.create_index(op.f('ix_ads_posted_at'), 'ads', ['posted_at'], unique=False)
    op.create_index(op.f('ix_ads_product_id'), 'ads', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ads_product_id'), table_name='ads')
    op.drop_index(op.f('ix_ads_posted_at'), table_name='ads')
    op.drop_column('ads', 'posted_platforms')
    op.drop_column('ads', 'posted_at')
    # ### end Alembic commands ###
