"""add logo_placement to brand_kits

Revision ID: 752addbf6f3c
Revises: a8c4bc3fda59
Create Date: 2026-07-08 13:41:16.081312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '752addbf6f3c'
down_revision: Union[str, None] = 'a8c4bc3fda59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brand_kits', sa.Column('logo_placement', sa.String(length=20), nullable=False, server_default=sa.text("'bottom-right'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('brand_kits', 'logo_placement')
    # ### end Alembic commands ###
