"""add campaign_id and campaign_phase to ads

Revision ID: 8b8ca879337d
Revises: 5360c8692a49
Create Date: 2026-07-08 20:41:02.156774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b8ca879337d'
down_revision: Union[str, None] = '5360c8692a49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.add_column('ads', sa.Column('campaign_phase', sa.String(length=20), nullable=True))
    op.create_index(op.f('ix_ads_campaign_id'), 'ads', ['campaign_id'], unique=False)
    op.create_foreign_key(None, 'ads', 'campaigns', ['campaign_id'], ['id'])
    op.create_index(op.f('ix_scheduled_posts_ad_id'), 'scheduled_posts', ['ad_id'], unique=False)
    op.create_index(op.f('ix_scheduled_posts_status'), 'scheduled_posts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheduled_posts_status'), table_name='scheduled_posts')
    op.drop_index(op.f('ix_scheduled_posts_ad_id'), table_name='scheduled_posts')
    op.drop_constraint(None, 'ads', type_='foreignkey')
    op.drop_index(op.f('ix_ads_campaign_id'), table_name='ads')
    op.drop_column('ads', 'campaign_phase')
    op.drop_column('ads', 'campaign_id')
    # ### end Alembic commands ###
