"""add logo_placement to brand_kits

Revision ID: a5bb1df8e04d
Revises: 752addbf6f3c
Create Date: 2026-07-08 13:44:45.715444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a5bb1df8e04d'
down_revision: Union[str, None] = '752addbf6f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
