"""add cancel_at_period_end

Revision ID: a8c4bc3fda59
Revises: 4394d363aa27
Create Date: 2026-07-08 09:34:20.106720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8c4bc3fda59'
down_revision: Union[str, None] = '4394d363aa27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'cancel_at_period_end')
    # ### end Alembic commands ###
