"""user invites: nullable password_hash, invite_token, invited_at

Revision ID: dc5f7f48d292
Revises: 8b8ca879337d
Create Date: 2026-07-10 19:50:08.752276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dc5f7f48d292'
down_revision: Union[str, None] = '8b8ca879337d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('invite_token', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('invited_at', sa.DateTime(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_invite_token'), 'users', ['invite_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_invite_token'), table_name='users')
    op.alter_column('users', 'password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'invited_at')
    op.drop_column('users', 'invite_token')
    # ### end Alembic commands ###
