/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Index_oldRouteImport } from './routes/index_old'
import { Route as DeveloperLoginRouteImport } from './routes/developer-login'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as DeveloperThemesRouteImport } from './routes/developer.themes'
import { Route as DeveloperTeamRouteImport } from './routes/developer.team'
import { Route as DeveloperSettingsRouteImport } from './routes/developer.settings'
import { Route as DeveloperPlatformsRouteImport } from './routes/developer.platforms'
import { Route as DeveloperOverviewRouteImport } from './routes/developer.overview'
import { Route as DeveloperModerationRouteImport } from './routes/developer.moderation'
import { Route as DeveloperModelsRouteImport } from './routes/developer.models'
import { Route as DeveloperCompaniesRouteImport } from './routes/developer.companies'
import { Route as DeveloperAssistantRouteImport } from './routes/developer.assistant'
import { Route as AppThemesGalleryRouteImport } from './routes/app.themes-gallery'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppScheduleRouteImport } from './routes/app.schedule'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppMyAdsRouteImport } from './routes/app.my-ads'
import { Route as AppModerationRouteImport } from './routes/app.moderation'
import { Route as AppConnectionsRouteImport } from './routes/app.connections'
import { Route as AppCampaignsRouteImport } from './routes/app.campaigns'
import { Route as AppCalendarRouteImport } from './routes/app.calendar'
import { Route as AppBrandKitRouteImport } from './routes/app.brand-kit'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAgentNivaRouteImport } from './routes/app.agent-niva'
import { Route as AppAdminRouteImport } from './routes/app.admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Index_oldRoute = Index_oldRouteImport.update({
  id: '/index_old',
  path: '/index_old',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperLoginRoute = DeveloperLoginRouteImport.update({
  id: '/developer-login',
  path: '/developer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperThemesRoute = DeveloperThemesRouteImport.update({
  id: '/developer/themes',
  path: '/developer/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperTeamRoute = DeveloperTeamRouteImport.update({
  id: '/developer/team',
  path: '/developer/team',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperSettingsRoute = DeveloperSettingsRouteImport.update({
  id: '/developer/settings',
  path: '/developer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperPlatformsRoute = DeveloperPlatformsRouteImport.update({
  id: '/developer/platforms',
  path: '/developer/platforms',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperOverviewRoute = DeveloperOverviewRouteImport.update({
  id: '/developer/overview',
  path: '/developer/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperModerationRoute = DeveloperModerationRouteImport.update({
  id: '/developer/moderation',
  path: '/developer/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperModelsRoute = DeveloperModelsRouteImport.update({
  id: '/developer/models',
  path: '/developer/models',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperCompaniesRoute = DeveloperCompaniesRouteImport.update({
  id: '/developer/companies',
  path: '/developer/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperAssistantRoute = DeveloperAssistantRouteImport.update({
  id: '/developer/assistant',
  path: '/developer/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThemesGalleryRoute = AppThemesGalleryRouteImport.update({
  id: '/app/themes-gallery',
  path: '/app/themes-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppScheduleRoute = AppScheduleRouteImport.update({
  id: '/app/schedule',
  path: '/app/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/app/products',
  path: '/app/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMyAdsRoute = AppMyAdsRouteImport.update({
  id: '/app/my-ads',
  path: '/app/my-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/app/moderation',
  path: '/app/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppConnectionsRoute = AppConnectionsRouteImport.update({
  id: '/app/connections',
  path: '/app/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/app/campaigns',
  path: '/app/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCalendarRoute = AppCalendarRouteImport.update({
  id: '/app/calendar',
  path: '/app/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBrandKitRoute = AppBrandKitRouteImport.update({
  id: '/app/brand-kit',
  path: '/app/brand-kit',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/app/analytics',
  path: '/app/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAgentNivaRoute = AppAgentNivaRouteImport.update({
  id: '/app/agent-niva',
  path: '/app/agent-niva',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/developer-login': typeof DeveloperLoginRoute
  '/index_old': typeof Index_oldRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agent-niva': typeof AppAgentNivaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand-kit': typeof AppBrandKitRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/moderation': typeof AppModerationRoute
  '/app/my-ads': typeof AppMyAdsRoute
  '/app/products': typeof AppProductsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/themes-gallery': typeof AppThemesGalleryRoute
  '/developer/assistant': typeof DeveloperAssistantRoute
  '/developer/companies': typeof DeveloperCompaniesRoute
  '/developer/models': typeof DeveloperModelsRoute
  '/developer/moderation': typeof DeveloperModerationRoute
  '/developer/overview': typeof DeveloperOverviewRoute
  '/developer/platforms': typeof DeveloperPlatformsRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/team': typeof DeveloperTeamRoute
  '/developer/themes': typeof DeveloperThemesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/developer-login': typeof DeveloperLoginRoute
  '/index_old': typeof Index_oldRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agent-niva': typeof AppAgentNivaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand-kit': typeof AppBrandKitRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/moderation': typeof AppModerationRoute
  '/app/my-ads': typeof AppMyAdsRoute
  '/app/products': typeof AppProductsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/themes-gallery': typeof AppThemesGalleryRoute
  '/developer/assistant': typeof DeveloperAssistantRoute
  '/developer/companies': typeof DeveloperCompaniesRoute
  '/developer/models': typeof DeveloperModelsRoute
  '/developer/moderation': typeof DeveloperModerationRoute
  '/developer/overview': typeof DeveloperOverviewRoute
  '/developer/platforms': typeof DeveloperPlatformsRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/team': typeof DeveloperTeamRoute
  '/developer/themes': typeof DeveloperThemesRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/developer-login': typeof DeveloperLoginRoute
  '/index_old': typeof Index_oldRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/app/admin': typeof AppAdminRoute
  '/app/agent-niva': typeof AppAgentNivaRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/brand-kit': typeof AppBrandKitRoute
  '/app/calendar': typeof AppCalendarRoute
  '/app/campaigns': typeof AppCampaignsRoute
  '/app/connections': typeof AppConnectionsRoute
  '/app/moderation': typeof AppModerationRoute
  '/app/my-ads': typeof AppMyAdsRoute
  '/app/products': typeof AppProductsRoute
  '/app/schedule': typeof AppScheduleRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/themes-gallery': typeof AppThemesGalleryRoute
  '/developer/assistant': typeof DeveloperAssistantRoute
  '/developer/companies': typeof DeveloperCompaniesRoute
  '/developer/models': typeof DeveloperModelsRoute
  '/developer/moderation': typeof DeveloperModerationRoute
  '/developer/overview': typeof DeveloperOverviewRoute
  '/developer/platforms': typeof DeveloperPlatformsRoute
  '/developer/settings': typeof DeveloperSettingsRoute
  '/developer/team': typeof DeveloperTeamRoute
  '/developer/themes': typeof DeveloperThemesRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/developer-login'
    | '/index_old'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/admin'
    | '/app/agent-niva'
    | '/app/analytics'
    | '/app/brand-kit'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/connections'
    | '/app/moderation'
    | '/app/my-ads'
    | '/app/products'
    | '/app/schedule'
    | '/app/settings'
    | '/app/themes-gallery'
    | '/developer/assistant'
    | '/developer/companies'
    | '/developer/models'
    | '/developer/moderation'
    | '/developer/overview'
    | '/developer/platforms'
    | '/developer/settings'
    | '/developer/team'
    | '/developer/themes'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/developer-login'
    | '/index_old'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/admin'
    | '/app/agent-niva'
    | '/app/analytics'
    | '/app/brand-kit'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/connections'
    | '/app/moderation'
    | '/app/my-ads'
    | '/app/products'
    | '/app/schedule'
    | '/app/settings'
    | '/app/themes-gallery'
    | '/developer/assistant'
    | '/developer/companies'
    | '/developer/models'
    | '/developer/moderation'
    | '/developer/overview'
    | '/developer/platforms'
    | '/developer/settings'
    | '/developer/team'
    | '/developer/themes'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/developer-login'
    | '/index_old'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/app/admin'
    | '/app/agent-niva'
    | '/app/analytics'
    | '/app/brand-kit'
    | '/app/calendar'
    | '/app/campaigns'
    | '/app/connections'
    | '/app/moderation'
    | '/app/my-ads'
    | '/app/products'
    | '/app/schedule'
    | '/app/settings'
    | '/app/themes-gallery'
    | '/developer/assistant'
    | '/developer/companies'
    | '/developer/models'
    | '/developer/moderation'
    | '/developer/overview'
    | '/developer/platforms'
    | '/developer/settings'
    | '/developer/team'
    | '/developer/themes'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  DeveloperLoginRoute: typeof DeveloperLoginRoute
  Index_oldRoute: typeof Index_oldRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  AppAdminRoute: typeof AppAdminRoute
  AppAgentNivaRoute: typeof AppAgentNivaRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBrandKitRoute: typeof AppBrandKitRoute
  AppCalendarRoute: typeof AppCalendarRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppConnectionsRoute: typeof AppConnectionsRoute
  AppModerationRoute: typeof AppModerationRoute
  AppMyAdsRoute: typeof AppMyAdsRoute
  AppProductsRoute: typeof AppProductsRoute
  AppScheduleRoute: typeof AppScheduleRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppThemesGalleryRoute: typeof AppThemesGalleryRoute
  DeveloperAssistantRoute: typeof DeveloperAssistantRoute
  DeveloperCompaniesRoute: typeof DeveloperCompaniesRoute
  DeveloperModelsRoute: typeof DeveloperModelsRoute
  DeveloperModerationRoute: typeof DeveloperModerationRoute
  DeveloperOverviewRoute: typeof DeveloperOverviewRoute
  DeveloperPlatformsRoute: typeof DeveloperPlatformsRoute
  DeveloperSettingsRoute: typeof DeveloperSettingsRoute
  DeveloperTeamRoute: typeof DeveloperTeamRoute
  DeveloperThemesRoute: typeof DeveloperThemesRoute
  AppIndexRoute: typeof AppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index_old': {
      id: '/index_old'
      path: '/index_old'
      fullPath: '/index_old'
      preLoaderRoute: typeof Index_oldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer-login': {
      id: '/developer-login'
      path: '/developer-login'
      fullPath: '/developer-login'
      preLoaderRoute: typeof DeveloperLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/themes': {
      id: '/developer/themes'
      path: '/developer/themes'
      fullPath: '/developer/themes'
      preLoaderRoute: typeof DeveloperThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/team': {
      id: '/developer/team'
      path: '/developer/team'
      fullPath: '/developer/team'
      preLoaderRoute: typeof DeveloperTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/settings': {
      id: '/developer/settings'
      path: '/developer/settings'
      fullPath: '/developer/settings'
      preLoaderRoute: typeof DeveloperSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/platforms': {
      id: '/developer/platforms'
      path: '/developer/platforms'
      fullPath: '/developer/platforms'
      preLoaderRoute: typeof DeveloperPlatformsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/overview': {
      id: '/developer/overview'
      path: '/developer/overview'
      fullPath: '/developer/overview'
      preLoaderRoute: typeof DeveloperOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/moderation': {
      id: '/developer/moderation'
      path: '/developer/moderation'
      fullPath: '/developer/moderation'
      preLoaderRoute: typeof DeveloperModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/models': {
      id: '/developer/models'
      path: '/developer/models'
      fullPath: '/developer/models'
      preLoaderRoute: typeof DeveloperModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/companies': {
      id: '/developer/companies'
      path: '/developer/companies'
      fullPath: '/developer/companies'
      preLoaderRoute: typeof DeveloperCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/assistant': {
      id: '/developer/assistant'
      path: '/developer/assistant'
      fullPath: '/developer/assistant'
      preLoaderRoute: typeof DeveloperAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/themes-gallery': {
      id: '/app/themes-gallery'
      path: '/app/themes-gallery'
      fullPath: '/app/themes-gallery'
      preLoaderRoute: typeof AppThemesGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/schedule': {
      id: '/app/schedule'
      path: '/app/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/products': {
      id: '/app/products'
      path: '/app/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/my-ads': {
      id: '/app/my-ads'
      path: '/app/my-ads'
      fullPath: '/app/my-ads'
      preLoaderRoute: typeof AppMyAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/moderation': {
      id: '/app/moderation'
      path: '/app/moderation'
      fullPath: '/app/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/connections': {
      id: '/app/connections'
      path: '/app/connections'
      fullPath: '/app/connections'
      preLoaderRoute: typeof AppConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/campaigns': {
      id: '/app/campaigns'
      path: '/app/campaigns'
      fullPath: '/app/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/calendar': {
      id: '/app/calendar'
      path: '/app/calendar'
      fullPath: '/app/calendar'
      preLoaderRoute: typeof AppCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/brand-kit': {
      id: '/app/brand-kit'
      path: '/app/brand-kit'
      fullPath: '/app/brand-kit'
      preLoaderRoute: typeof AppBrandKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/app/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/agent-niva': {
      id: '/app/agent-niva'
      path: '/app/agent-niva'
      fullPath: '/app/agent-niva'
      preLoaderRoute: typeof AppAgentNivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  DeveloperLoginRoute: DeveloperLoginRoute,
  Index_oldRoute: Index_oldRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  AppAdminRoute: AppAdminRoute,
  AppAgentNivaRoute: AppAgentNivaRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBrandKitRoute: AppBrandKitRoute,
  AppCalendarRoute: AppCalendarRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppConnectionsRoute: AppConnectionsRoute,
  AppModerationRoute: AppModerationRoute,
  AppMyAdsRoute: AppMyAdsRoute,
  AppProductsRoute: AppProductsRoute,
  AppScheduleRoute: AppScheduleRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppThemesGalleryRoute: AppThemesGalleryRoute,
  DeveloperAssistantRoute: DeveloperAssistantRoute,
  DeveloperCompaniesRoute: DeveloperCompaniesRoute,
  DeveloperModelsRoute: DeveloperModelsRoute,
  DeveloperModerationRoute: DeveloperModerationRoute,
  DeveloperOverviewRoute: DeveloperOverviewRoute,
  DeveloperPlatformsRoute: DeveloperPlatformsRoute,
  DeveloperSettingsRoute: DeveloperSettingsRoute,
  DeveloperTeamRoute: DeveloperTeamRoute,
  DeveloperThemesRoute: DeveloperThemesRoute,
  AppIndexRoute: AppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
